// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYPtJlCOSFBe9yNv7CdRps7h3YLk_yMvk',
    appId: '1:696205065808:web:eb23047e798f50a08a1b55',
    messagingSenderId: '696205065808',
    projectId: 'combinedai',
    authDomain: 'combinedai.firebaseapp.com',
    storageBucket: 'combinedai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACvKrRXvDZhPqEx-dA5idvdf919GN_Mqo',
    appId: '1:696205065808:android:0db1e5e15495f06c8a1b55',
    messagingSenderId: '696205065808',
    projectId: 'combinedai',
    storageBucket: 'combinedai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs-5aqVBNwjT8_TxDr5p3R_4JGRiBTwow',
    appId: '1:696205065808:ios:37f9c77b705800d58a1b55',
    messagingSenderId: '696205065808',
    projectId: 'combinedai',
    storageBucket: 'combinedai.firebasestorage.app',
    iosBundleId: 'com.example.combinedAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs-5aqVBNwjT8_TxDr5p3R_4JGRiBTwow',
    appId: '1:696205065808:ios:37f9c77b705800d58a1b55',
    messagingSenderId: '696205065808',
    projectId: 'combinedai',
    storageBucket: 'combinedai.firebasestorage.app',
    iosBundleId: 'com.example.combinedAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYPtJlCOSFBe9yNv7CdRps7h3YLk_yMvk',
    appId: '1:696205065808:web:7853d4a010ef96a88a1b55',
    messagingSenderId: '696205065808',
    projectId: 'combinedai',
    authDomain: 'combinedai.firebaseapp.com',
    storageBucket: 'combinedai.firebasestorage.app',
  );

}