import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Make sure this file is generated by Firebase
import 'pages/auth_page.dart'; // Replace with the actual path to your AuthPage

void main() async {
  // Ensure Flutter engine bindings are initialized before Firebase setup
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Combined AI', // Set app title
      theme: ThemeData(
        primarySwatch: Colors.blue, // Customize theme color if needed
      ),
      home: const AuthPage(), // Set AuthPage as the initial page
    );
  }
}
